[package]
name = "rusoto-sample"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.14.0", features = ["full"] }
rusoto_core = "0.47.0"
rusoto_dynamodb = "0.47.0"
serde = "1.0.130"
serde_json = "1.0.71"
serde_dynamo = "2.4.0"
